### ISSUE TITLE
Moonrealm loading as a biome and not a separate realm.

### ISSUE THREAD

**Issue by Routhinator** [paramat/moonrealm#1]
Maybe I'm missing something here but when I load this into mapgen 7 it's mixin into my world as a biome and taking over spawn.. is this normal? I interpretation from the forums is that this was a seperate realm.

**Comment by paramat** [comment]
Sorry for the delay. The forum post may be misleading. The mod now forces singlenode mapgen whatever you choose at world creation, so the is world completely dedicated to a moonrealm that extends 8000 nodes in every direction from (0,0,0).

**Comment by Routhinator** [comment]
Is it possible to make it work as a seperate realm from the terrestrial one? Maybe add rockets or portals to get there?

**Comment by paramat** [comment]
Yes i think so and i intend to do that, this mod is neglected, will work on it once 0.4.13 is out.

**Comment by Routhinator** [comment]
Sounds great. I'd like to include it in tekkest and see rockets added to technic.
